### ISSUE TITLE
git clone - compile failed

### ISSUE THREAD

**Issue by rcampbellnc** [dalenguyen/angular-store-locator#2]
on Win10 box
git, node, npm, angular, agm all installed
cloned repo: git clone https://github.com/dalenguyen/angular-store-locator.git
ng serve fails to compile with error:
`Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:31:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:201:32)
    at ServeCommand.<anonymous> (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:53:25)
    at Generator.next (<anonymous>)
    at C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:52:16)
    at Object.<anonymous> (C:\Users\rcampbellnc\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:127:23)`

**Comment by dalenguyen** [comment]
Hi @rcampbellnc, It could be because of the angular-cli version on your computer. Please update it. You can read about this here: https://stackoverflow.com/questions/49810580/error-local-workspace-file-angular-json-could-not-be-found

Please let me know if it works.
